### ISSUE TITLE
Not working since Gateway 1.0?

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/influxdb-bridge#8]
I haven't had time to investigate this, I should get some time next week.

**Comment by tim-hellhake** [comment]
I just installed it on a fresh 1.0 gateway.
No problems so far.

**Comment by tim-hellhake** [comment]
@chas-iot Any news on this?

**Comment by tim-hellhake** [comment]
I guess not :grimacing: 
If the problem appears again feel free to reopen the issue.

**Comment by chas-iot** [comment]
I did a little tracing. Does the socket depend on TCP or TCPv6?
When I run `sudo netstat -tunlp` on the gateway, there is a listener on tcp6 port 8080 but no listener on plain tcp port 8080.

In the logs, the influx adapter now writes out
> run-app.log.2021-02-27:2021-02-27 14:50:23.135 INFO   : influxdb-bridge: Loading add-on influxdb-bridge from /home/pi/.webthings/addons/influxdb-bridge
> run-app.log.2021-02-27:2021-02-27 14:50:23.137 INFO   : influxdb-bridge: Connecting to influx at localhost
> run-app.log.2021-02-27:2021-02-27 14:50:23.138 INFO   : influxdb-bridge: Create database if it does not exist
> run-app.log.2021-02-27:2021-02-27 14:50:23.447 INFO   : influxdb-bridge: Connecting to gateway
> run-app.log.2021-02-27:2021-02-27 14:50:23.448 INFO   : influxdb-bridge: Probing port 8080

Previously, I saw it continue
> run-app.log.2020-12-03:2020-12-03 01:28:18.942 INFO   : influxdb-bridge: Probing port 8080
> run-app.log.2020-12-03:2020-12-03 01:28:19.791 INFO   : influxdb-bridge: Connecting to websocket of weather-20c0b7bdab70ca2cc9c844a0d74a3af0bbf41c3e
> run-app.log.2020-12-03:2020-12-03 01:28:19.856 INFO   : influxdb-bridge: Connecting to websocket of zb-286d97000101d27f
> run-app.log.2020-12-03:2020-12-03 01:28:19.857 INFO   : influxdb-bridge: Connecting to websocket of RuuviTag-e8c780e741c9
> run-app.log.2020-12-03:2020-12-03 01:28:20.125 INFO   : influxdb-bridge: Connected to ws://localhost:8080/things/weather-20c0b7bdab70ca2cc9c844a0d74a3af0bbf41c3e
> run-app.log.2020-12-03:2020-12-03 01:28:20.127 INFO   : influxdb-bridge: Connected to ws://localhost:8080/things/zb-286d97000101d27f
> run-app.log.2020-12-03:2020-12-03 01:28:20.128 INFO   : influxdb-bridge: Connected to ws://localhost:8080/things/RuuviTag-e8c780e741c9`

**Comment by tim-hellhake** [comment]
> Does the socket depend on TCP or TCPv6

It depends on the OS and kernel configuration.
If you use Linux with ipv6 enabled, the default is a socket that listens on ipv4 and ipv6.
As you can see [here](https://github.com/WebThingsIO/gateway/blob/9228b0726ebad525ead4256cdfdc151e331f2f5e/src/app.ts#L145) the gateway uses the default.
The underlying [webthings-client](https://github.com/tim-hellhake/webthings-client/blob/df589483e830a3252a1dfd5d8845d5381893f49a/src/webthings-client.ts#L16) uses localhost to connect to the gateway.
Depending on the ipv6 config of the kernel, `localhost` either resolves to `127.0.0.1` or `::1`.

> When I run sudo netstat -tunlp on the gateway, there is a listener on tcp6 port 8080 but no listener on plain tcp port 8080.

That's because the ipv6 socket also accepts ipv4 connections.

> Previously, I saw it continue

Since 86eaff0 the adapter uses a single WebSocket to get all updates from the gateway.

> In the logs, the influx adapter now writes out

I don't see any problems in the log.
Do you see new data in your InfluxDB?

**Comment by chas-iot** [comment]
Thanks. I turned on debug and nothing.
Then I added a few console.logs (in webthings-client) and can see that the connection is successful but no messages are received. I created a new access token in the gateway to see if that could be the issue, but still nothing.
I’ll submit a pull request to webthings-client with one additional console.log as I think the information is valuable.

**Comment by tim-hellhake** [comment]
> I created a new access token in the gateway to see if that could be the issue, but still nothing

Strange, I'll try to reproduce it with a fresh installation later.

**Comment by tim-hellhake** [comment]
Turns out that you can't access the general `things` websocket if your token is restricted to a limited number of devices.
I assume your token was only for a few devices.
The adapter is now connecting to the individual websockets of the devices.

**Comment by chas-iot** [comment]
> I assume your token was only for a few devices.

Yep, as accessing all devices is supposed to be a performance drain.

**Comment by chas-iot** [comment]
Updated. And it’s working!

Awesome, thanks @tim-hellhake
